### ISSUE TITLE
readme improvements #1 (suggested by @rchikhi)

### ISSUE THREAD

**Issue by md5sam** [makovalab-psu/RecoverY#1]
@rchikhi says : 

regarding the input

     r1.fastq : Enriched raw reads (first in pair) 
     r2.fastq : Enriched raw reads (second in pair) 
     kmers_from_reads : kmer counts from DSK for r1.fastq
     trusted_kmers : kmer counts from DSK for human Y single copy genes

it'd be helpful to have some example command line usage on how to produce kmers_from_reads and trusted_kmers :)

also, in the Script section of the README, you could mention that those scripts are not only included in the repository, but are also part of the "recovery.py", they're automatically run by the program, and the user could also consider them separately for custom needs.

**Comment by rchikhi** [comment]
also rename the "data" folder to "example" or "test"

**Comment by md5sam** [comment]
Updates : 
- Added a 'dependency' folder with DSK binary and a script to run DSK to produce :
                          
      kmers_from_reads

- Updated README to reflect this. 
- Improved the Script section of README as suggested


I'm currently unable to rename "data" folder to "example"  because RecoverY expects the input folder to be called "data". I've opened [Issue #2](https://github.com/makovalab-psu/RecoverY/issues/2) for custom I/O folder names. 

I'm marking this thread as "closed".
